### ISSUE TITLE
Hub translators need to handle errors from missing device translators

### ISSUE THREAD

**Issue by danielrischar** [openT2T/translators#164]
Hub translators support creating individual device translators as part of theor getPlatforms() call.  Now that we don't list the device translators as dependencies of the hub in package.json, we run the risk of some translators not existing, in which case the device should be skipped.  Right now OpenT2T throws an error like "Cannot find module 'opent2t-translator-com-wink-lightbulb'".

Basically, if you install a binary switch translator, you also get the onboarder and the hub, but if you also got a lightbulb on the hub, we'll error out now.

Not sure if we have a way of bubbling up an error "Hey, we would support this device if you'd just install a translator for it" or whether we just want to ignore it.

**Comment by arjun-msft** [comment]
A proper error message is returned saying could not find translator x.
