### ISSUE TITLE
Wink Thermostat Integration tests fail

### ISSUE THREAD

**Issue by shalinijoshi19** [openT2T/translators#167]
Fail with 
1. before
   failed with "OpenT2T.createTranslatorAsync is not a function"
      Object.createTranslator (test.js:21:20)
    Test.test.before [as fn] (c:/opent2t/sj/translators/node_modules/opent2t-device-thermostat/thermostatTests.js:36:25)
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by arjun-msft** [comment]
all tests are now passing.
