### ISSUE TITLE
Insteon hub logs and ignores get_status failures

### ISSUE THREAD

**Issue by danielrischar** [openT2T/translators#171]
If the get_status call in the Insteon hub translator fails, the error is logged to the console and ignored.  Line 100, and line 412.

These errors should be thrown so that the app can tell that the device is incommunicado (this happens if the device itself is turned off) rather than thinking that the communication is still okay.

**Comment by m-chau** [comment]
Fix applied in https://github.com/openT2T/translators/pull/187.
