### ISSUE TITLE
Update all translators to new design

### ISSUE THREAD

**Issue by tjaffri** [openT2T/translators#36]
Update translators for breaking changes in the new design, including:

  - Node module exports
  - Translator metadata in package.json
  - Schema composability, and directory structure changes that result from it
  - Properties and signals
  - Hub devices

**Comment by tjaffri** [comment]
We should spin up a separate branch to do these changes, and coordinate across repos.

**Comment by tjaffri** [comment]
This wiki contains more information about the new design: https://github.com/openT2T/opent2t/wiki/Modules-and-Packages

**Comment by sanjaiganesh** [comment]
@tjaffri @arjun-msft Isn't this is something to be distributed across all of us, once Wink Thermostat with new design PR is merged. ?

**Comment by arjun-msft** [comment]
This issue is now out of date.
