### ISSUE TITLE
Figure out design to put tests at the "schema" level rather than the translator level

### ISSUE THREAD

**Issue by tjaffri** [openT2T/translators#57]
All the tests are common for the translators in a given schema e.g. look at discussion here: https://github.com/openT2T/translators/pull/56#discussion_r75394429

We should figure out a way to have a single set of tests for a schema that runs for all the translators in that schema, and flags any that are "different". We should also have a way to write extra depth tests beyond the schema tests for any particular translator we want.

**Comment by tjaffri** [comment]
Note that this might be harder than we think... see unit tests under https://github.com/openT2T/translators/tree/dev/org.opent2t.sample.thermostat.superpopular.

It turns out that while they LOOK similar, there are subtle differences between tests for both thermostats:

1. Wink does some strange rounding, so the wink automated test does set/gets and compares the values to be "approximately equal". Nest returns exact info so that is not needed there... we could do an "approximately equal" test for nest as well... but that is a difference nevertheless.

2. Nest does not support "target temperature" so we are doing some averaging there. Nest does support it. So that's another clear difference.

I still think we should have schema level tests, but maybe allow somebody to "override" the schema level test for a particular translator. So when we run tests at the schema level for all the translators in that schema... we run all the schema level tests, skip any schema level tests that are overridden for a particular translator (and run the translator's override) and then finally run any ADDITIONAL tests that only exist for a particular translator.

**Comment by arjun-msft** [comment]
This has been completed.
