### ISSUE TITLE
Create a Test thermostat translator (similar to test lamp)

### ISSUE THREAD

**Issue by tjaffri** [openT2T/translators#64]

**Comment by tjaffri** [comment]
1. This will be under translators/org.opent2t.sample.thermostat.superpopular/ in the dev branch
2. Folder will be called org.opent2t.test.thermostat
3. Inside you should have a README, package.json and tests similar to wink and nest.
4. Name of the package inside package.json should be opent2t-translator-org-opent2t-test-thermostat
5. You should also make sure there are automated tests for the test thermostat and they should pass (return fixed fake values to make the test pass)

**Comment by arjun-msft** [comment]
We need to figure out what our dev story is before we do this.
